dist: trusty
language: java
cache:
    directories:
        - "$HOME/.m2"
install:
    - curl -o $HOME/.m2/settings.xml https://raw.githubusercontent.com/trajano/trajano/master/src/site/resources/settings.xml
    - mvn dependency:go-offline
jdk:
    - oraclejdk8
    - openjdk8
addons:
  apt:
    packages:
      - wget
      - pkg-config
sudo: required
script:
    - jdk_switcher use oraclejdk8
    - jdk_switcher use openjdk8
    - ./bootstrap.sh
